const genres = [
  "Platform",
  "Shooter",
  "Fighting",
  "Beat 'em up",
  "Stealth",
  "Survival",
  "Survival",
  "Rhythm",
  "Battle Royale",
  "Survival Horror",
  "Metroidvania",
  "Text Adventure",
  "Graphic Adventure",
  "Visual Novel",
  "Interactive Movie",
  "Real-time 3D Adventure",
  "Action RPG",
  "MMORPG",
  "Roguelike",
  "Tactical RPG",
  "Sandbox RPG",
  "First-person Party-based RPG",
  "JRPG",
  "Monster Tamer",
  "Construction and Management Simulation",
  "Life Simulation",
  "Vehicle Simulation",
  "4X",
  "Artillery",
  "Auto Battler (Auto Chess)",
  "Multiplayer Online Battle Arena (MOBA)",
  "Real-time Strategy (RTS)",
  "Real-time Tactics (RTT)",
  "Tower Defense",
  "Turn-based Strategy (TBS)",
  "Turn-based Tactics (TBT)",
  "Wargame",
  "Grand Strategy Wargame",
  "Racing",
  "Sports",
  "Competitive",
  "MMO",
  "Board or Card Game",
  "Breakout Clone",
  "Casino",
  "Casual",
  "Digital Collectible Card Game",
  "Gacha",
  "Horro",
  "Idle",
  "Logic",
  "Party",
  "Photography",
  "Programming",
  "Social Deduction",
  "Trivia",
  "Typing",
  "Sandbox",
  "Creative",
  "Open World",
];

export default genres;
